/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.frontendapp.presentation;

import co.unicauca.frontendapp.access.UserRepositorio;
import co.unicauca.frontendapp.entities.User;
import co.unicauca.frontendapp.entities.enumPrograma;
import co.unicauca.frontendapp.entities.enumRol;
import co.unicauca.frontendapp.facade.AuthFacade;
import co.unicauca.frontendapp.observer.AuthObserver;
import co.unicauca.frontendapp.service.Service;
import co.unicauca.frontendapp.utility.EmailValidator;
import co.unicauca.frontendapp.utility.PasswordUtils;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Acer
 */
public class GuiRegister extends javax.swing.JFrame implements AuthObserver {

    private final AuthFacade facade;
    //BookingService bookingService = new BookingService(new BookingRepository() {});
    Service service = new Service(new UserRepositorio() {
    });

    static GuiLogin login;

    public GuiRegister() {
        login = new GuiLogin();
        initComponents();
        this.facade = new AuthFacade();
        this.facade.addObserver(this);
        //this.service = new Service(new UserRepositorio);

        setTitle("Registrar Usuario");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 500);
        setLocationRelativeTo(null);

        getContentPane().removeAll();
        setLayout(new BorderLayout());

        // ------------------ HEADER ------------------
        JLabel header = new JLabel("Registrar Usuario", SwingConstants.CENTER);
        header.setFont(new Font("Segoe UI", Font.BOLD, 22));
        header.setOpaque(true);
        header.setBackground(new Color(72, 201, 176));
        header.setForeground(Color.WHITE);
        header.setBorder(BorderFactory.createEmptyBorder(15, 10, 15, 10));
        add(header, BorderLayout.NORTH);

        // ------------------ FORMULARIO ------------------
        JPanel formPanel = new JPanel(new GridBagLayout());
        formPanel.setBackground(new Color(245, 245, 245));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        //  Filas del formulario 
        addRow(formPanel, gbc, 0, new JLabel("Nombres:"), txtNombres);
        addRow(formPanel, gbc, 1, new JLabel("Apellidos:"), txtApellidos);
        addRow(formPanel, gbc, 2, new JLabel("Celular:"), txtCelular);
        addRow(formPanel, gbc, 3, new JLabel("Programa:"), comboBoxPrograma);
        addRow(formPanel, gbc, 4, new JLabel("Rol:"), comboBoxRol);
        addRow(formPanel, gbc, 5, new JLabel("Email:"), txtEmail);
        addRow(formPanel, gbc, 6, new JLabel("Contraseña:"), txtContrasenia);

        // ------------------ BOTONES ------------------
        JPanel buttonPanel = new JPanel();
        personalizarBoton(btnRegistrar, new Color(72, 201, 176));
        personalizarBoton(btnIniciarSesion, new Color(93, 173, 226));
        buttonPanel.add(btnRegistrar);
        buttonPanel.add(btnIniciarSesion);

        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        formPanel.add(buttonPanel, gbc);

        add(formPanel, BorderLayout.CENTER);

        // Refrescar
        revalidate();
        repaint();
    }

    @Override
    public void dispose() {
        this.facade.removeObserver(this);
        super.dispose();
    }

    private void addRow(JPanel panel, GridBagConstraints gbc, int row,
            Component label, JComponent field) {
        label.setFont(new Font("Segoe UI", Font.BOLD, 14));
        label.setForeground(new Color(60, 60, 60));

        gbc.gridx = 0;
        gbc.gridy = row;
        gbc.weightx = 0.3;
        panel.add(label, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.7;
        panel.add(field, gbc);
    }

    private void personalizarBoton(JButton boton, Color bgColor) {
        boton.setBackground(bgColor);
        boton.setForeground(Color.WHITE);
        boton.setFont(new Font("Segoe UI", Font.BOLD, 14));
        boton.setFocusPainted(false);
        boton.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombres = new javax.swing.JLabel();
        LabelApellidos = new javax.swing.JLabel();
        LabelPrograma = new javax.swing.JLabel();
        comboBoxPrograma = new javax.swing.JComboBox<>();
        LabelCelular = new javax.swing.JLabel();
        LabelContrasenia = new javax.swing.JLabel();
        comboBoxRol = new javax.swing.JComboBox<>();
        LabelRol = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNombres.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelNombres.setText("Nombres :");
        LabelNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelApellidos.setBackground(new java.awt.Color(153, 255, 51));
        LabelApellidos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelApellidos.setText("Apellidos :");
        LabelApellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelPrograma.setBackground(new java.awt.Color(153, 255, 51));
        LabelPrograma.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelPrograma.setText("Programa :");
        LabelPrograma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGENIERIA_SISTEMAS", "INGENIERIA_ELECTRONICA_TELECOMUNICACIONES", "AUTOMATICA_INDUSTRIAL", "TECNOLOGIA_TELEMATICA" }));
        comboBoxPrograma.setToolTipText("");
        comboBoxPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProgramaActionPerformed(evt);
            }
        });

        LabelCelular.setBackground(new java.awt.Color(153, 255, 51));
        LabelCelular.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelCelular.setText("Celular :");
        LabelCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelContrasenia.setBackground(new java.awt.Color(153, 255, 51));
        LabelContrasenia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelContrasenia.setText(" Contraseña :");
        LabelContrasenia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", "Coordinador", "Jefe_Departamento" }));

        LabelRol.setBackground(new java.awt.Color(153, 255, 51));
        LabelRol.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelRol.setText("Rol :");
        LabelRol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelEmail.setBackground(new java.awt.Color(153, 255, 51));
        LabelEmail.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelEmail.setText("Email :");
        LabelEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 51, 153));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(102, 102, 255));
        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.setBorder(new javax.swing.border.MatteBorder(null));
        btnIniciarSesion.setMaximumSize(new java.awt.Dimension(300, 300));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboBoxPrograma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProgramaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
//         try {
//        String nombres = txtNombres.getText();
//        String apellidos = txtApellidos.getText();
//        String celular = txtCelular.getText();
//        String seleccionadoPrograma = comboBoxPrograma.getSelectedItem().toString();
//        enumPrograma programa = enumPrograma.valueOf(seleccionadoPrograma);
//
//        // Convertir String a enumRol
//        String seleccionadoRol = comboBoxRol.getSelectedItem().toString();
//        enumRol rol = enumRol.valueOf(seleccionadoRol);  
//        String email = txtEmail.getText();
//        String contrasenia = new String(txtContrasenia.getPassword());
//
//        User nuevoUsuario = new User(nombres, apellidos, celular, programa, rol, email, contrasenia);
//             JOptionPane.showMessageDialog(this, nuevoUsuario.toString());
//        boolean exito = service.registrarUsuario(nuevoUsuario);
//
//        if (exito) {
//            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito!");
//        } else {
//            JOptionPane.showMessageDialog(this, "Error en el registro. Verifique los datos.");
//        }
//
//    } catch (Exception ex) {
//        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
//    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        try {
            String nombres = txtNombres.getText().trim();
            String apellidos = txtApellidos.getText().trim();
            String celular = txtCelular.getText().trim();
            String seleccionadoPrograma = comboBoxPrograma.getSelectedItem().toString();
            enumPrograma programa = enumPrograma.valueOf(seleccionadoPrograma);
            String seleccionadoRol = comboBoxRol.getSelectedItem().toString();
            enumRol rol = enumRol.valueOf(seleccionadoRol);
            String email = txtEmail.getText().trim();
            String contrasenia = new String(txtContrasenia.getPassword());
            User nuevoUsuario = new User(nombres, apellidos, celular, programa, rol, email, contrasenia);

            if (!EmailValidator.esCorreoInstitucional(nuevoUsuario.getEmail())) {
                JOptionPane.showMessageDialog(this,
                        "El dominio del correo debe ser @unicauca.edu.co",
                        "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (!PasswordUtils.validarContrasenia(nuevoUsuario.getContraseña())) {
                JOptionPane.showMessageDialog(this,
                        """
        La contraseña debe cumplir con los siguientes requisitos:
        - Al menos 6 caracteres
        - Al menos una letra mayúscula
        - Al menos un número
        - Al menos un carácter especial (@#$%^&+=!¿?.,;:_-)
        - No debe contener espacios
        """,
                        "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            btnRegistrar.setEnabled(false);

            new javax.swing.SwingWorker<Boolean, Void>() {
                @Override
                protected Boolean doInBackground() {
                    return facade.register(nuevoUsuario);
                }

                @Override
                protected void done() {
                    btnRegistrar.setEnabled(true);
                    try {
                        Boolean resultado = get();
                        if (resultado != null && resultado) {
                            JOptionPane.showMessageDialog(null,
                                    "Usuario registrado exitosamente",
                                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

                            // Limpiar todos los campos
                            limpiarCampos();
                        } else {
                            JOptionPane.showMessageDialog(null,
                                    "No se pudo registrar el usuario",
                                    "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null,
                                "Error al procesar el registro: " + ex.getMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }.execute();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        txtContrasenia.setText("");

        // Resetear los ComboBox al primer elemento
        if (comboBoxPrograma.getItemCount() > 0) {
            comboBoxPrograma.setSelectedIndex(0);
        }

        if (comboBoxRol.getItemCount() > 0) {
            comboBoxRol.setSelectedIndex(0);
        }

        // Opcional: poner el foco en el primer campo
        txtNombres.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelContrasenia;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNombres;
    private javax.swing.JLabel LabelPrograma;
    private javax.swing.JLabel LabelRol;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboBoxPrograma;
    private javax.swing.JComboBox<String> comboBoxRol;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onUserRegistered(User user) {
        javax.swing.SwingUtilities.invokeLater(()
                -> javax.swing.JOptionPane.showMessageDialog(this,
                        "¡Usuario registrado: " + user.getNombre() + "!",
                        "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE)
        );
    }

    @Override
    public void onUserRegistrationFailed(String message) {
        javax.swing.SwingUtilities.invokeLater(()
                -> javax.swing.JOptionPane.showMessageDialog(this,
                        "Registro fallido: " + message,
                        "Registro", javax.swing.JOptionPane.WARNING_MESSAGE)
        );
    }
}
